---
title: "Stress factors in Canada depending on the location in Canada and age"
author: "Sevnur Kulak"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: pdf_document

abstract: ' Stress has been one of the main important health concerns over the years.
  It is important to identify specific stress factors in different age groups and
  in different locations so that any actions can be taken for its reduction. This
  paper focuses on several stress factors in Canada, looking specifically at different
  age groups and locations to see if there are any common stress factors within these
  groups. 
  keywords:mental health; stress; mental health factors; Canada; age; day-to-day life; work; financial stress; time pressure; schoolwork; health concerns; family problems'

---


# Introduction
Stress has been one of the biggest health concerns of human life although its consequences are still unforeseeable. There are various triggering factors of stress depending on the country, location in a country, income, education, health, family, social life, work-life balance, and more. It is important to assess these factors to be able to identify the main source of stress factors so that necessary actions can be taken such as new policy implementation. 
This paper focuses on the main stress factors in Canada. Utilizing a dataset from Open Data - Government of Canada, the paper identifies the main stress factors in each state, aiming to find clusters of specific factors depending on the geographical location. It also investigates the stress factors depending on the age range and if any of the specific stress factors cluster around depending on individuals’ age. The initial hypothesis is that there will be specific stress factors that are commonly seen in different age groups and different locations within Canada. 
The paper finds … 
The paper proceeds with the Data section in which I discuss the features of the variables and the data itself as well as the graphs and tables. The section of Model will then explain an appropriate model for the data. The paper will then proceed with the Results section in which the analysis of the data, graphs, and tables will be conducted. The discussion section will summarize the paper itself, highlighting the key findings and will elaborate on the strength and weaknesses of the paper as well as potential further research topics. 
 



# Data


# Model


# Results


# Discussion


# Appendix


# References